### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by elemis** [patrickvuarnoz/nova-beautify#1]
Is it possible to make configurations on how Beautify works?

**Comment by patrickvuarnoz** [comment]
Yes, in principle it is possible and the plugin could offer the same config options that js-beautify offers (see https://github.com/beautify-web/js-beautify). 

I'd see two options to achieve that: 

a) One way would be to configure it via preference pane globally and/or per project. But maybe you do not want to set those settings globally for all syntaxes. And to offer all options for each syntax separately makes the config unneccessarily complicated.

b) Another, maybe better option would be to support config options via .jsbeautifyrc config file. That would allow very fine tuned settings for each syntax. But that requires knowledge of all the possible config options of js-beautify.

Do you have some specific settings in mind, what do you want to configure?

**Comment by elemis** [comment]
Actually it works mostly as I wish, as it is. But .jsbeautifyrc config file would be great for minor tweaks.

**Comment by patrickvuarnoz** [comment]
Decided against the .jsbeautifyrc config for the following reasons:

- It requires file access entitlements that are otherwise not required
- It is not transparent what options exist
- There is no way to use .jsbeautifyrc as a global config

Instead I implemented a basic set of global preferences. A new version is in the Nova Extensions Library as of now. Hope it contains the option you were looking for. If not, please let me know.

**Comment by elemis** [comment]
Thank you for this update it's great! 

I was just wondering if it's possible to add an option to delete empty lines? Right now Beautify adds empty lines before and after <head> and <body> sections and I couldn't disable this with the existing settings. Maybe I'm missing something?

**Comment by patrickvuarnoz** [comment]
There's the option "preserve existing line-breaks" (at the bottom of each list of config-options per syntax). If this is ticked, it won't remove existing empty lines. 

Have you tried this?

**Comment by elemis** [comment]
I have it unchecked and it removes the unnecessary empty lines if I have any, which is great.

But the space before and after head and body sections gets added no matter if that option is enabled or disabled after Beautifying. I normally don't have spaces there. I guess I need the option of disabling this.

**Comment by patrickvuarnoz** [comment]
I can confirm that it does that. I think it has to do with the option `extra_liners` which I did not implement:

> extra_liners: List of tags (defaults to [head,body,/html] that should have an extra newline before them.

I could not fully test and confirm how the options `inline `, `unformatted `, `content_unformatted ` and `extra_liners ` work and how to override the defaults there - i.e. I tried to override them, but it didn't behave as expected. I'll have a look into it and see how these settings can be enabled.

**Comment by elemis** [comment]
Thanks for looking into it. One more thing: Would it possible to have the option "beautify on save"?

**Comment by patrickvuarnoz** [comment]
There's already another "issue" concerning this. See here: https://github.com/patrickvuarnoz/nova-beautify/issues/2

**Comment by patrickvuarnoz** [comment]
Add few additional config options. In the 'extra lines before' option you can remove the tags you do not want an extra line before. That should solve your problem.

**Comment by GwynethLlewelyn** [comment]
> In the 'extra lines before' option you can remove the tags you do not want an extra line before.

@patrickvuarnoz I know you've closed this issue as solved, but I have an issue here: I don't want _any_ tags to get an extra line before them! This means essentially passing JS Beautify an empty list. However, I can't seem to accomplish that: it looks like Nova, when saving the preferences, checks if a field is empty, and, if it is, replaces it by the default value.

Granted, I'm really quite rusty in Nova plugin extension development (so many new things to learn!), but, AFAICS, your own code doesn't 'enforce' anything (i.e. no 'revert to default if empty' option — as said, AFAICS!!), so I'd guess it's being done by Nova itself (?).

**Comment by patrickvuarnoz** [comment]
@GwynethLlewelyn 

This seems to be a bug. The default is obviously automatically restored when you empty that text field. The extension itself does nothing there. I filed a bug report with Panic and opened a separate issue for the problem here at GitHub.

To get ahead with your formatting you can simply enter a comma (i.e. ",") in the field "Extra lines before". In my test that worked.

**Comment by GwynethLlewelyn** [comment]
Oh, clever, clever... that comes from _not_ being a JavaScript programmer. I wouldn't have dreamed up that simple workaround!

Thanks, that surely worked for me as well. And thanks for the update!
