### ISSUE TITLE
Return to Top of Document After Format

### ISSUE THREAD

**Issue by TechRemarker** [patrickvuarnoz/nova-beautify#10]
While of course having a format on save option would be by far the most ideal option like other similar systems, in the meantime, when using the extension it seems to always jump to the bottom of the document after selecting all and formatting rather going to the top of the document. Dreamweaver for decades has had the best beautifer, and plenty of websites work great as well but for extensions for Coda, then Atom, then Nova they have always been problematic. This is the first extension that seems to work very well at least with standard HTML/PHP/CSS mixed code, so hoping the return to top is added soon, and again while I'm sure it's on the todo, hopefully format on save will be added soon, which will be a life saver for me may fellow developers whos use it.

**Comment by patrickvuarnoz** [comment]
Hi Chris

Thanks for your issue report. I share your pain with the missing beautifier for Nova – I would have expected that they include something so fundamental themselves. But no, they didn't and don't plan to do so. That's why I ported the Beautify-Formatter I was used to from Brackets to Nova. 

Unfortunately I'm currently a bit under water with my normal work but I will have a look at the issue as soon as I have time.

Best
Patrick

**Comment by patrickvuarnoz** [comment]
Hi Chris

Actually you don't have to "select all" and then "format", you can directly "format" without a selection which formats the whole document. But I've seen that the scroll position is off when doing so.

I now released a new version of the extension with format on save option. This also optimizes the cursor position after formatting. When you do a format on save or a format without text selection it keeps the cursor position within the document so you can just continue typing where you left off.

Hope this serves your needs.

Best
Patrick

**Comment by TechRemarker** [comment]
Updated to latest version. Can't seem to get to work, maybe I have to restart? Also in settings don't see PHP which I presume is one the most popular use cases, so I imagine checking "HTML" includes PHP documents which is most all WordPress files, the most popular CMS in the world. Can try uninstalling and reinstalling maybe?

**Comment by patrickvuarnoz** [comment]
I'm sorry but PHP is not supported. JS-Beautify is not built to format PHP so I can't guarantee that when applying HTML formatting to a PHP-HTML file (a) everything will still work and (b) the format will make sense.

But I'm thinking about an option to manually specify further file/syntax types which then would allow to also add php-html at one's own risk.
