### ISSUE TITLE
[Feature Request]: Consider allowing to load an external JS Beautify script/automatic updater

### ISSUE THREAD

**Issue by GwynethLlewelyn** [patrickvuarnoz/nova-beautify#12]
First of all, thanks for doing this Nova extension :) It's tremendously useful, especially when I have things that Prettier doesn't format properly (that's why it _is_ an _opinionated_ formatter, after all) — such as HTML5 (long story...)

Anyway, I've noticed that you include `js-beautify.js` directly, and call its functionality by including the file in the extension-provided file. I noticed that you currently have a slightly outdated version of thos e script, and wondered if I couldn't replace it with a new version without touching your code.

Some extensions (a few of my old ones included!) simply allow an external script to be set via the Preferences panel; your extension could try to use that first, and fall back to the internally distributed version otherwise. This is mimicking what others do, even though the ones I know about actually include an external _command-line application_, which isn't the way you're using JS Beautify — therefore, there might be some Nova-imposed sandboxing limitations to do just that.

An alternative would be to allow the JS Beautify JavaScript file to be remotely included from a CDN. That way, you could always get the 'latest' version automatically, without the need to upgrade the extension and publish a new release. Again, I'm not sure if you can do that from within the sandboxed extension, either.

I know that you _can_ execute things on the Mac — or else those other extensions (including mine!) would not be able to run the content of a file and capture the output from it and present it inside the Nova editor. I'm assuming that you can do the same — essentially, using `wget` or `curl` to check for the 'latest' version, and download it automatically, or possibly manually via a 'check update' button on the Extension Preferences) to the temporary workspace set up by Nova for the current run of your extension.

Running JS Beautify from the CLI (inside Node) might also help those preferring to stick to configurations using `.jsbeautifyrc` files...

Can such a thing be implemented?

Thanks for any insights

**Comment by patrickvuarnoz** [comment]
Hi @GwynethLlewelyn 

Thanks for your comments. What I don't like about providing own versions of JS Beautify or implementing the ability to download those from a CDN or working with `.jsbeautifyrc` files is that this requires additional rights for the extension such as `Read and Write Files`, `Launch Subprocesses` or `Send Network Requests`. 

Those additional rights could theoretically easily be misused and require trust from the users working with the extension. Keeping everything sandboxed solves that problem. No damage can be done that way. So I'd like to keep it that way for the moment.

But I'm happy for notifications from users about new versions of JS Beautify. Currently the extension uses 1.14.7, the latest version would be 1.14.8. It seems I missed that one. The extension will be updated soon with that version.

**Comment by GwynethLlewelyn** [comment]
Oh, I see — you do have a point there, one shouldn't ask for more permissions than are actually needed. Now I understand why you _include_ `js-beautify.js` directly: that way, you avoid asking for permissions to run anything on a subprocess, since it's just an included file, nothing else.

Hmm. That is a most clever trick, and I totally understand your arguments in favour of that approach.

I withdraw my feature request, then, and hope that, over time, you'll just allow us to tweak more and more JS Beautify parameters from the Preferences pane. That should be enough in 99.9% of all cases, I guess.

My original reason for this request was merely because JS Beautify might support additional (third-party!) languages beyond the common set (JS, HTML, CSS...) — but that would require pulling in extra JS, which would obviously not work with your extension.

I guess that what I _really_ want is Nova to directly support [UniBeautify](https://unibeautify.com/) 😄 But these guys have exactly the _opposite_ philosophy — run _everything_ outside the main script, which is just an API layer to provide a uniform syntax to call many completely different code beautifiers. Clever 😊 I guess that I should do my own extension to support UniBeautify, though...
