### ISSUE TITLE
Add configuration setting for indent_empty_lines

### ISSUE THREAD

**Issue by carlospero** [patrickvuarnoz/nova-beautify#15]
JS-Beautify added this "indent_empty_lines" feature in v1.9.1 in March 2019. Default is **false**.
https://github.com/beautifier/js-beautify/issues/1322

It would facilitate unbroken indentation guides.
Could you please consider adding this as a configuration boolean to be passed to the script?

<img width="207" alt="Screenshot 2024-01-08 at 10 05 21 AM" src="https://github.com/patrickvuarnoz/nova-beautify/assets/1698951/f8a136e5-a4ce-4078-9886-09d31cebcca6">

**Comment by patrickvuarnoz** [comment]
Hi Carlos, thanks for your feedback. I quickly implemented the missing config option together with some other options that were also missing. A new version of the extension is already published. Enjoy.
