### ISSUE TITLE
Clips cannot be beautified and crashed Nova

### ISSUE THREAD

**Issue by manuelthomsen** [patrickvuarnoz/nova-beautify#3]
I tried beautifying one of my clips and Nova simply crashed

**Comment by patrickvuarnoz** [comment]
Hi manuelthomsen, can you provide steps to reproduce that?

**Comment by manuelthomsen** [comment]
*   Open web project
  *   3 tabs  ( HTML / CSS / Preview ) on an ultra wide
  *   Open clips ( on the left side panel )
( this specific clip is HTML and has a trigger but no has shortcut )

  *   Edit clip ( global clip inside of a clip folder )
  *   Cmd + P ( command palette )
  *   Typed beau ( for beautify )
  *   Pressed enter
  *   Crash



Tested if I could reproduce it again with these steps, and crashed again as expected



Regards Manuel

**Comment by patrickvuarnoz** [comment]
Funny thing... I cannot bring the command palette to show me any of the beautify options while I'm editing a clip. It's actually also not supposed to do so, since the commands are only activated when the editor has focus.  

Are you also on Nova 4.2, Build 236512 and extension version 1.2.0?

If no, please consider updating. 
If yes, I need you to provide screenshots so that I can replay it 1:1.

**Comment by manuelthomsen** [comment]
I’ll check and send you screenshots. I’m 4.2 but the I’m not sure about the extension

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by manuelthomsen** [comment]
Had to do a bit of censuring.
Updated to 4.3 same
Beautify is at the latest version.

Same process, same project.

Crashed when I press enter to beautify from the command palette

![Screenshot 2021-01-28 at 12 51 04](https://user-images.githubusercontent.com/57219617/106140969-c340cc80-616f-11eb-81f3-e886a773d169.png)
![Screenshot 2021-01-28 at 12 50 08](https://user-images.githubusercontent.com/57219617/106140978-c50a9000-616f-11eb-9a85-2680c6d4b0d1.png)

**Comment by patrickvuarnoz** [comment]
Sorry, screenshots did not come through to GitHub. Maybe you have to upload them directly here at GitHub instead of replying by mail.

**Comment by manuelthomsen** [comment]
I updated the post on Github

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by patrickvuarnoz** [comment]
Thanks. So far I can follow you. How about the command palette. What has focus when you hit cmd+p and type "beau"? Is anything selected in the clip editor? Or the HTML / CSS editor in the background or even the preview window?

**Comment by manuelthomsen** [comment]
Ah... I think I’m the error. Writing beau defaults to report error. Still closes the project if I say continue to report the bug. Would be nice to be able to beautify clips though. Sorry for wasting your time mate 😅

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by patrickvuarnoz** [comment]
I see what you mean. Just quick typing + hitting enter... Never mind.

I think it is a limitation of Nova to not offer the commands from the extensions. But it would make perfectly sense. Maybe you can send them a feature request.

**Comment by manuelthomsen** [comment]
I will. Thanks for the help anyway. 🙏

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
