### ISSUE TITLE
Mac Keyboard Shortcut not working in Nova

### ISSUE THREAD

**Issue by bwminick** [patrickvuarnoz/nova-beautify#9]
Hello,

According to Nova, the keyboard shortcut to use Beautify is (Shift)(Option)F.  However, this inserts the following symbol instead: **Ï**, instead of actually triggering Beautify.

Can this please be changed to another shortcut that works?  Thank you!  :-)

**Comment by patrickvuarnoz** [comment]
Hi bwminick,

I can confirm that I have the same problem. I think it's related to the newest version of Nova (8.0 or 8.1). I filed a bug request with Panic. 

If you need a quick solution then go to Nova Preferences > Key Bindings > Extensions and change the keyboard shortcut for the format command to `ctrl-shift-f`. This seems to work.

Best,
Patrick

**Comment by bwminick** [comment]
Hi Patrick,

Thank you very much!  I’ll give that a try…. 😊

Byron

>

**Comment by patrickvuarnoz** [comment]
Hi bwminick,

I got a confirmation from Panic. It's a bug they introduced with the VIM support in Nova 8. A fix should arrive with the next update of Nova.

Best,
Patrick
